config/routes.rb
Rails.application.routes.draw do
  resources :chapter_events

  get 'dashboard/index'
  get 'dashboard/upload_roster'
  post 'dashboard/process_roster'
  get 'dashboard/at_a_glance'

  devise_for :users
  get 'welcome/index'

  resources :contacts

  root 'welcome#index'

end

app/controllers/dashboard_controller.rb
# Displays the dashboard for signed-in chapter leaders.
#
# Authentication is required.
class DashboardController < ApplicationController
  before_filter :authenticate_user!

  def index
    @newest = Contact.newest
  end

  # Upload a member roster for processing.
  def upload_roster
  end

  def process_roster
    newcsv = params[:roster_csv].tempfile
    if RosterImporter.new.process(newcsv)
      flash[:notice] = 'Import completed successfully!'
    else
      flash[:notice] = 'Could not recognize file format.'
    end
    redirect_to dashboard_index_path
  end

  # At-a-glance view of useful member statistics
  def at_a_glance
  end

  # Upload an event attendance report for processing.
  def upload_event
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/at_a_glance.html.erb
<div class="row">
  <div class="large-12 columns">
    <h1>Membership At a Glance</h1>
  </div>
  <div class="large-4 columns">
    <h2>Member Age</h2>
    <table>
      <tr>
        <th>
          Newest Join
        </th>
        <td>
          <%= Contact.newest_join_date %>
        </td>
      </tr>
      <tr>
        <th>
          Median Join
        </th>
        <td>
          <%= Contact.median_age %>          
        </td>
      </tr>
      <tr>
        <th>
          Oldest Join
        </th>
        <td>
          <%= Contact.oldest_join_date %>
        </td>
      </tr>
    </table>
  </div>
  <div class="large-4 columns">
    
  </div>
  <div class="large-4 columns">
    
  </div>
</div>

app/views/dashboard/index.html.erb
<div class="row">
  <div class="large-12 columns">
    <% if current_user.first_name? %>
    <h1>Welcome back, <%= current_user.first_name %>!</h1>
    <% else %>
    <h1>Welcome back!</h1>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="large-12 columns">
    <h2>Newest Members</h2>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Company</th>
          <th>City</th>
          <th>Category</th>
          <th>Join Date</th>
        </tr>
      </thead>
    <% @newest.each do |m| %>
      <tbody>
        <tr>
          <td><%= link_to m.full_name, m %></td>
          <td><%= link_to m.company_name, m.website_url %></td>
          <td><%= m.city %></td>
          <td><%= m.member_cat_name %></td>
          <td><%= m.member_since.strftime('%D') %></td>
        </tr>
      </tbody>
    <% end %>
    </table>
  </div>
</div>

app/views/dashboard/process_roster.html.erb
<h1>Roster Processed!</h1>

app/views/dashboard/upload_roster.html.erb
<div class="row">
  <div class="large-12 medium-12 columns">
	  <h1>Upload a Roster</h1>
    <%= form_tag dashboard_process_roster_path, multipart: true do %>
      <label for="roster_csv">File to Upload</label>
      <%= file_field_tag :roster_csv %>
      <%= submit_tag 'Upload File', class: [:radius, :button] %>
    <% end %>
  </div>
</div>