config/routes.rb
Rails.application.routes.draw do
  resources :chapter_events

  get 'dashboard/index'
  get 'dashboard/upload_roster'
  post 'dashboard/process_roster'
  get 'dashboard/at_a_glance'

  devise_for :users
  get 'welcome/index'

  resources :contacts

  root 'welcome#index'

end

app/models/chapter_event.rb
class ChapterEvent < ActiveRecord::Base
end

app/controllers/chapter_events_controller.rb
class ChapterEventsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_chapter_event, only: [:show, :edit, :update, :destroy]

  # GET /chapter_events
  # GET /chapter_events.json
  def index
    @chapter_events = ChapterEvent.all
  end

  # GET /chapter_events/1
  # GET /chapter_events/1.json
  def show
  end

  # GET /chapter_events/new
  def new
    @chapter_event = ChapterEvent.new
  end

  # GET /chapter_events/1/edit
  def edit
  end

  # POST /chapter_events
  # POST /chapter_events.json
  def create
    @chapter_event = ChapterEvent.new(chapter_event_params)

    respond_to do |format|
      if @chapter_event.save
        format.html { redirect_to @chapter_event, notice: 'Chapter event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @chapter_event }
      else
        format.html { render action: 'new' }
        format.json { render json: @chapter_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chapter_events/1
  # PATCH/PUT /chapter_events/1.json
  def update
    respond_to do |format|
      if @chapter_event.update(chapter_event_params)
        format.html { redirect_to @chapter_event, notice: 'Chapter event was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @chapter_event }
      else
        format.html { render action: 'edit' }
        format.json { render json: @chapter_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chapter_events/1
  # DELETE /chapter_events/1.json
  def destroy
    @chapter_event.destroy
    respond_to do |format|
      format.html { redirect_to chapter_events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapter_event
      @chapter_event = ChapterEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chapter_event_params
      params.require(:chapter_event).permit(:name, :date)
    end
end

app/helpers/chapter_events_helper.rb
module ChapterEventsHelper
end

app/views/chapter_events/_form.html.erb
<%= form_for(@chapter_event) do |f| %>
  <% if @chapter_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chapter_event.errors.count, "error") %> prohibited this chapter_event from being saved:</h2>

      <ul>
      <% @chapter_event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chapter_events/edit.html.erb
<h1>Editing chapter_event</h1>

<%= render 'form' %>

<%= link_to 'Show', @chapter_event %> |
<%= link_to 'Back', chapter_events_path %>

app/views/chapter_events/index.html.erb
<h1>Listing chapter_events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chapter_events.each do |chapter_event| %>
      <tr>
        <td><%= chapter_event.name %></td>
        <td><%= chapter_event.date %></td>
        <td><%= link_to 'Show', chapter_event %></td>
        <td><%= link_to 'Edit', edit_chapter_event_path(chapter_event) %></td>
        <td><%= link_to 'Destroy', chapter_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chapter event', new_chapter_event_path %>

app/views/chapter_events/new.html.erb
<h1>New chapter_event</h1>

<%= render 'form' %>

<%= link_to 'Back', chapter_events_path %>

app/views/chapter_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @chapter_event.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @chapter_event.date %>
</p>

<%= link_to 'Edit', edit_chapter_event_path(@chapter_event) %> |
<%= link_to 'Back', chapter_events_path %>