config/routes.rb
Rails.application.routes.draw do
  resources :chapter_events

  get 'dashboard/index'
  get 'dashboard/upload_roster'
  post 'dashboard/process_roster'
  get 'dashboard/at_a_glance'

  devise_for :users
  get 'welcome/index'

  resources :contacts

  root 'welcome#index'

end

app/views/shared/_flashes.html.erb
<div class="row">
  <div class="large-12 columns">
  <% if flash[:notice] %>
    <div data-alert class="alert-box">
      <%= flash[:notice] %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>

  <% if flash[:alert] %>
    <div data-alert class="alert-box info">
      <%= flash[:alert] %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><a href="/">Engage-o-tron</a></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <% if user_signed_in? %>
    <ul class="right">
      <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
    </ul>
    <% end %>
    
    <ul class="right">
      <li class="active"><a href="#">Right Button Active</a></li>
      <li class="has-dropdown">
        <a href="#">Right Button Dropdown</a>
        <ul class="dropdown">
          <li><a href="#">First link in dropdown</a></li>
        </ul>
      </li>
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
      <li><%= link_to 'Contacts', :contacts %></li>
      <li class="has-dropdown">
        <a href="#">Import</a>
        <ul class="dropdown">
          <li><%= link_to 'Member Roster', dashboard_upload_roster_path %></li>
          <li><%= link_to 'Event Attendance Report', '' %></li>
        </ul>
      </li>
      <li><%= link_to 'At-A-Glance', dashboard_at_a_glance_path %></li>
    </ul>
    
  </section>
</nav>