config/routes.rb
Rails.application.routes.draw do
  resources :chapter_events

  get 'dashboard/index'
  get 'dashboard/upload_roster'
  post 'dashboard/process_roster'
  get 'dashboard/at_a_glance'

  devise_for :users
  get 'welcome/index'

  resources :contacts

  root 'welcome#index'

end

app/models/contact.rb
# Contact records represent both members and nonmembers.
#
# These records are generally created programatically as the result of
# importing a membership roster or an event attendance report.
#
class Contact < ActiveRecord::Base
  MEMBER_TYPE = {
  }
  validates :email, uniqueness: true, allow_nil: true
  validates :member_num, uniqueness: true, allow_nil: true

  default_scope { order('last_name ASC, first_name ASC') }
  scope :newest, -> { unscoped.where(member: true).order('member_since DESC').limit(5) }

  # Scopes for join date reporting
  scope :join_dates, -> { unscoped.where(member: true).order(:member_since).pluck(:member_since) }
  scope :last_joined, -> { unscoped.where(member: true).order('member_since DESC').limit(1) }
  scope :first_joined, -> { unscoped.where(member:true).order('member_since ASC').limit(1) }

  # Returns the contact's full name (first and last names).
  def full_name
    [first_name, last_name].join(' ')
  end

  # Returns the contact's name in directory format (last name first).
  def directory_name
    [last_name, first_name].join(', ')
  end

  # Returns median join date of members
  def self.median_age
    times = join_dates.map { |x| x.to_time.to_i }
    # If no members, return N/A
    if times.empty?
      'N/A'
    # If even array, mean the two middle values.
    elsif times.size.even?
      Time.at((times[times.size / 2] + times[times.size / 2 - 1]) / 2).to_date.stftime('%D')
    # If odd array, use the true median.
    else
      Time.at(times[times.size / 2]).to_date.strftime('%D')
    end
  end

  def self.newest_join_date
    last_joined.empty? ? 'N/A' : last_joined.first.member_since.strftime('%D')
  end

  def self.oldest_join_date
    first_joined.empty? ? 'N/A' : first_joined.first.member_since.strftime('%D')
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        # format.json { render action: 'show', status: :created, location: @contact }
      else
        format.html { render action: 'new' }
        # format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        # format.json { render action: 'show', status: :ok, location: @contact }
      else
        format.html { render action: 'edit' }
        # format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully deleted.' }
      # format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = Contact.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white
  # list through.
  def contact_params
    params.require(
      :contact
    ).permit(
      :first_name,
      :last_name,
      :company_name,
      :address1,
      :address2,
      :city,
      :state,
      :zip_code,
      :phone,
      :member,
      :member_type,
      :member_since
    )
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
  def member_category
    render partial: 'member_category',
           locals: { color: @contact.member_cat_name.downcase.gsub(/ /, '-') }
  end
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :company_name %><br>
    <%= f.text_field :company_name %>
  </div>
  <div class="field">
    <%= f.label :address1 %><br>
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br>
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip_code %><br>
    <%= f.text_field :zip_code %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :member %><br>
    <%= f.check_box :member %>
  </div>
  <div class="field">
    <%= f.label :member_type %><br>
    <%= f.number_field :member_type %>
  </div>
  <div class="field">
    <%= f.label :member_since %><br>
    <%= f.date_select :member_since %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/_member_category.html.erb
<i class="fa fa-group <%= color %>"></i> <%= @contact.member_cat_name %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<div class="row">
  <div class="large-12 medium-12 columns">
<h1>Listing contacts (<%= @contacts.count %> total)</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Company name</th>
      <th>City</th>
      <th>Member</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.first_name %></td>
        <td><%= contact.last_name %></td>
        <td><%= contact.company_name %></td>
        <td><%= contact.city %></td>
        <% if contact.member? %>
          <td><i class="fa fa-check"></i></td>
        <% else %>
          <td></td>
        <% end %>
        <td>
          <a href="<%= contact_path(contact) %>" class="tiny radius button split">View <span data-dropdown="drop-<%= contact.id %>"></span></a><br>
          <ul id="drop-<%= contact.id %>" class="f-dropdown" data-dropdown-content>
            <li>
              <%= link_to '<i class="fa fa-edit"></i> Edit'.html_safe, edit_contact_path(contact) %>
            </li>
            <li>
              <%= link_to '<i class="fa fa-trash-o"></i> Delete'.html_safe, contact, method: :delete, data: {confirm: "This can't be undone. Are you sure?"}%>
            </li>
          </ul>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>
</div>
</div>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<div class="row">
  <div class="large-12 medium-12 small-12 columns">
    <% if notice %>
      <div data-alert class="alert-box">
        <%= notice %>
        <a href="#" class="close">&times;</a>
      </div>
    <% end %>
  
    <h1><%= @contact.full_name %></h1>
    <h2><%= @contact.company_name %></h2>
  
    <% if @contact.member_since > Time.now %>
      <div data-alert class="alert-box info">
        This member is currently awaiting membership approval.
      </div>
    <% end %>
  
    <p>
      <%= member_category %><br>
      Member since <%= @contact.member_since.strftime('%D') %>
    </p>
  </div>
</div>
  
<div class="row">
  <div class="large-6 medium-6 small-12 columns">
    <h3>Mailing Address</h3>
    <p>
      <%= @contact.address1 %><br>
      <% unless @contact.address2.empty? %>
      <%= @contact.address2 %><br>
      <% end %>
      <%= @contact.city %>, <%= @contact.state %> <%= @contact.zip_code %>
    </p>
  </div>
  <div class="large-6 medium-6 small-12 columns">
    <h3>Telephone</h3>
    <p><%= link_to @contact.phone, "tel:#{@contact.phone.gsub(/\W/,'')}" %></p>
  </div>
</div>
  
<div class="row">
  <div class="large-12 medium-12 small-12 columns">
    <h3>Event Attendance</h3>
    <table>
      <thead>
        <tr>
          <th>Event</th>
          <th>Date</th>
          <th>Location</th>
          <th>Distance</th>
          <th>Attended?</th>
        </tr>
      </thead>
      <tbody>
      </tbody>
    </table>
  
    <%= link_to 'Edit', edit_contact_path(@contact) %> |
    <%= link_to 'Back', contacts_path %>
  </div>
</div>